pulibrary/lib_jobs

- .rubocop.yml
- app/controllers/data_sets_controller.rb
- app/models/data_set.rb
- app/models/staff_directory_difference.rb
- app/models/staff_directory_generator.rb
- app/views/data_sets/index.html.erb
- app/views/data_sets/show.html.erb
- config/staff_directory.yml
- db/migrate/20201204151642_add_fields_to_dataset.rb
- db/schema.rb
- spec/models/data_set_spec.rb
- spec/models/staff_directory_difference_spec.rb
- spec/models/staff_directory_generator_spec.rb
- spec/requests/data_set_request_spec.rb
Also archiving Staff differences, both added and removed
> Adding data sets into the system when staff directories are generated

- config/initializers/content_security_policy.rb
This was necessary for the deployment into the production environment with Webpack and Vue support.
> Adjusting the Content Security Policy for the usage of LUX in the production environment

- Capfile
- Gemfile
- Gemfile.lock
- config/schedule.rb
- lib/tasks/lib_jobs.rake
Setting up staff directory to run at 11:05 UTC or 6:05am EDT 7:05am EST
Moving sqllite to development & test section since that is the only place is is used
> Adding whenever gem

- config/cas.yml
Fixes something went wrong error when you log onto the staging server
> Add staging configuration for cas

- app/controllers/absolute_ids_controller.rb
- app/controllers/application_controller.rb
- app/controllers/data_sets_controller.rb
- app/models/ability.rb
- config/routes.rb
- db/migrate/20210217203226_add_status_to_data_set.rb
- db/schema.rb
- spec/models/data_set_spec.rb
- spec/rails_helper.rb
- spec/requests/data_set_request_spec.rb
Gets the latest successful version of the passed in type and returns the data to the user
This route is for either cas signed in users or token authenticated users only
Moved token authentication methods into application controller so they can be utilized by both absolute_ids and data_sets
fixes #56
> Adding latest to DataSet controller

- README.md
> Introducing documentation for deploying and testing AbID functionality within the staging environment

- app/controllers/absolute_ids/repositories/containers_controller.rb
- app/javascript/components/absolute_id_form.vue
- app/javascript/components/absolute_id_marc_form.vue
- config/routes.rb
Increases coverage by removing inaccessible code.
> Remove unused ContainersController code

- .circleci/config.yml
- .lando.yml
- README.md
- app/models/absolute_id/batch.rb
- config/application.rb
- config/database.yml
- config/lando_env.rb
- db/schema.rb
- lib/tasks/server.rake
- spec/requests/absolute_id_request_spec.rb
We're finding inconsistencies in dev/test vs staging/prod, so best to standardize on one database.
> Use Postgres for dev/test

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/absolute_ids_controller.rb
- app/jobs/absolute_id_create_job.rb
- app/views/barcodes/index.html.erb
- spec/support/devise.rb
- spec/support/system_specs.rb
- spec/system/barcodes_system_spec.rb
I chose this over a unit test because there's a lot of moving parts I
don't really understand and this gets to the kind of coverage we need in
order to support refactors.
> Add barcode system spec.

- app/views/absolute_ids/index.html.erb
- spec/system/absolute_id_system_spec.rb
This also fixes a bug with displaying the system display for AbIDs.
> Add synchronization to system spec.

- app/models/absolute_id/session.rb
- spec/system/absolute_id_system_spec.rb
> Adjust report to user request.

- .circleci/config.yml
- .eslintrc.js
- .gitignore
- app/javascript/__tests__/components/absolute_id_aspace_status.spec.js
- app/javascript/__tests__/setup.js
- babel.config.js
- jest.config.js
- package.json
- yarn.lock
> Introduces Jest for testing Vue Components

- Gemfile
- Gemfile.lock
- app/models/access_token.rb
- app/models/alma_person_feed.rb
- app/models/alma_xml_person.rb
- app/models/oit_person_feed.rb
- config/application.rb
- lib/tasks/lib_jobs.rake
- spec/fixtures/rest_researcher.xsd
- spec/fixtures/rest_user.xsd
- spec/fixtures/rest_users.xsd
- spec/models/access_token_spec.rb
- spec/models/alma_person_feed_spec.rb
- spec/models/alma_xml_person_spec.rb
- spec/models/oit_person_feed_spec.rb
- spec/rails_helper.rb
Adds an AccessToken class that goes out to an oath source and asks for a token.
Adds an OITPersonFeed that goes out to the OIT api store and retrieves json data for the request.
> Adding classes to access OIT person data

- app/jobs/absolute_ids/create_model_job.rb
- spec/system/absolute_id_system_spec.rb
> Ensure AbIDs increment in a batch.

- db/migrate/20210506183059_change_index_in_absolute_ids_to_be_integer.rb
- db/schema.rb
Sorting doesn't work without this.
> Convert index to integer type.

- app/mailers/application_mailer.rb
- app/mailers/finance_mailer.rb
- app/models/alma_xml_fund_list.rb
- app/models/alma_xml_invoice.rb
- app/models/alma_xml_invoice_list.rb
- app/models/voucher_feed.rb
- config/environments/production.rb
- config/environments/staging.rb
- spec/mailers/finance_mailer_spec.rb
- spec/models/alma_xml_invoice_list_spec.rb
- spec/models/alma_xml_invoice_spec.rb
- spec/models/voucher_feed_spec.rb
Quote onbase csv and change name to correct spelling of Library
Updaet environments for smtp
change email to testing group for now
> Making updates based on testing

- app/jobs/absolute_ids/session_synchronize_job.rb
- spec/fixtures/archives_space/repositories_top_containers_search.json
- spec/fixtures/archives_space/repositories_top_containers_search_orphan.json
- spec/jobs/absolute_ids/session_synchronize_job_spec.rb
- spec/support/stub_aspace_client.rb
> Ignore orphan containers for validation

- app/models/alma_xml_invoice.rb
- app/models/alma_xml_invoice_list.rb
- app/views/finance_mailer/report.html.erb
- spec/mailers/finance_mailer_spec.rb
- spec/models/alma_xml_invoice_list_spec.rb
- spec/models/voucher_feed_spec.rb
Also added vendor code along with vendor id to the status report and email
> Updating onbase report to have vendor code instead of vendor id

- app/models/alma_xml_invoice_list.rb
- app/models/voucher_feed.rb
- app/views/finance_mailer/report.html.erb
- app/views/finance_mailer/report.text.erb
- spec/mailers/finance_mailer_spec.rb
- spec/models/voucher_feed_spec.rb
Also updating email to say no invoices were present
fixes #182
> Updating to not produce files if no invoices are present

- app/models/peoplesoft_voucher/alma_xml_invoice.rb
- spec/fixtures/invalid_invoice.xml
- spec/fixtures/invoice_export_202118300518.xml
- spec/models/alma_xml_invoice_list_spec.rb
- spec/models/alma_xml_invoice_spec.rb
> Skipping items with no fund lines

- app/models/peoplesoft_voucher/alma_xml_invoice.rb
> Remove the use of the turnary operator

- app/models/alma_fund_adjustment/file_transfer.rb
- app/models/alma_people/alma_person_feed.rb
- app/models/alma_sftp.rb
- app/models/peoplesoft_voucher/alma_xml_invoice_list.rb
- app/models/peoplesoft_voucher/voucher_feed.rb
- config/alma_ftp.yml
- config/application.rb
- config/peoplesoft.yml
- lib/tasks/lib_jobs.rake
- spec/models/alma_fund_adjustment/file_transfer_spec.rb
Extracted the code to start an sftp into a class for reuse
Moved environment variables for alma ftp and peoplesoft samba share into config file
refs #183
> Adding Alma Fund Adjustment job

- app/models/alma_invoice_status/file_converter.rb
- app/models/alma_people/alma_person_feed.rb
- app/models/peoplesoft_voucher/voucher_feed.rb
- config/peoplesoft.yml
- lib/tasks/lib_jobs.rake
Also cleaning up some commented out code and moving one more location to use the AlmaSftp class
> Adding rake task for alma invoice status

- config/peoplesoft.yml
change it to be xml instead of csv
> Fix the default input pattern for invoice status

- app/models/peoplesoft_voucher/alma_xml_invoice_list.rb
- app/models/peoplesoft_voucher/finance_xml_invoice.rb
- spec/models/peoplesoft_voucher/voucher_feed_spec.rb
stops us from creating empty onbase and peoplesoft files
fixes #192
> Changing empty to valid invoices

- config/deploy/production.rb
- config/schedule.rb
Needs to go live on Sunday based on https://docs.google.com/document/d/16rYUZZTp6LleHBx6ijq0rcUD8vbnIyADt8keTf2bAy4/edit
ref #191
> Add the Alma Voucher feed processing to  the crontab

- app/models/alma_people/alma_xml_person.rb
- spec/models/alma_xml_person_spec.rb
> Changing graduate student's addresses to be treated like faculty and staff

- app/models/peoplesoft_voucher/alma_xml_fund_list.rb
- spec/fixtures/finance_invoice.xml
- spec/fixtures/invoice_export_202118300518.xml
Updated the regexes to account for negative amounts.
> account for negative amounts in voucher feed

- app/models/peoplesoft_voucher/alma_xml_invoice.rb
- spec/fixtures/finance_invoice.xml
- spec/models/peoplesoft_voucher/alma_xml_invoice_list_spec.rb
- spec/models/peoplesoft_voucher/alma_xml_invoice_spec.rb
- spec/models/peoplesoft_voucher/voucher_feed_spec.rb
> fix voucher id generation

- yarn.lock
Fixes a dependabot alert that couldn't automatically generate a PR
> Bump version of @rails/webpacker

- .gitignore
- Gemfile
- Gemfile.lock
- app/models/alma_pod_records/alma_pod_file_list.rb
- app/models/alma_pod_records/alma_pod_job.rb
- app/models/alma_pod_records/alma_pod_sender.rb
- config/pod.yml
- lib/tasks/lib_jobs.rake
- spec/models/alma_pod_records/alma_pod_job_spec.rb
- spec/models/alma_pod_records/alma_pod_sender_spec.rb
> Send pod records

- Gemfile
- Gemfile.lock
- app/models/alma_renew/alma_renew_list.rb
- app/models/alma_renew/item.rb
- app/models/alma_renew/renew_job.rb
- config/alma_ftp.yml
- config/config.yml
- config/schedule.rb
- lib/tasks/lib_jobs.rake
- spec/fixtures/empty_renew.csv
- spec/fixtures/renew.csv
- spec/models/alma_renew/alma_renew_list_spec.rb
- spec/models/alma_renew/item_spec.rb
- spec/models/alma_renew/renew_job_spec.rb
Have the ability to download a report(s) from alma FTP
Have the ability to translate a line of the report into NCIP XML
Have the ability to send those to Alma
fixes #262
> Adding in NCIP renewal

- app/models/alma_pod_records/alma_pod_file_list.rb
- spec/models/alma_pod_records/alma_pod_file_list_spec.rb
> Don't send empty files to POD

- app/models/alma_pod_records/alma_pod_file_list.rb
- app/models/alma_pod_records/alma_pod_job.rb
- app/models/marc_collection.rb
- spec/models/alma_pod_records/alma_pod_file_list_spec.rb
- spec/models/alma_pod_records/alma_pod_job_spec.rb
This should allow us to process full dumps.
> Only handle one POD file at a time

- app/mailers/finance_mailer.rb
- app/models/peoplesoft_bursar/credit_report.rb
- app/models/peoplesoft_bursar/fine_report.rb
- app/models/peoplesoft_bursar/report.rb
- spec/models/peoplesoft_bursar/job_spec.rb
> Update subject line of Bursar emails

- app/mailers/transaction_error_mailer.rb
- config/config.yml
- spec/mailers/finance_mailer_spec.rb
- spec/mailers/transaction_error_spec.rb
Connected to #314 
See also PR on princeton_ansible: https://github.com/pulibrary/princeton_ansible/pull/3056
> Move emails into ansible vault

- Capfile
- Gemfile
- Gemfile.lock
- Rakefile
- config/honeybadger.yml
> Configure Honeybadger

- config/schedule.rb
Update the name for the second rake task
closes #342
> set the same time for credits and fines

- docs/peoplesoft_voucher/README.md
Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
Co-authored-by: Mark Zelesky <mzelesky@users.noreply.github.com>
Co-authored-by: Jane Sandberg <js7389@users.noreply.github.com>
> Adding voucher feed documentation

- docs/alma_fund_adjustment/README.md
Initial blush.  Still need the Alma side atleast
> Adding Alma fund adjustment docs

- app/models/alma_renew/item.rb
- spec/models/alma_renew/item_spec.rb
> Setting 7pm local as the time on the due date

- config/schedule.rb
Branch to be temporarily deployed during fiscal period close period from 6/17-7/1.
> Remove Voucher Feed from cron schedule

- app/models/alma_renew/alma_renew_list.rb
- app/models/alma_renew/item.rb
- app/models/alma_renew/renew_job.rb
- docs/alma_renew/README.md
- spec/fixtures/renew_no_id_no_expiration.csv
- spec/fixtures/renew_no_user_id.csv
- spec/models/alma_renew/alma_renew_list_spec.rb
- spec/models/alma_renew/item_spec.rb
- spec/models/alma_renew/renew_job_spec.rb
> Ncip renewal oo

- docs/testing.md
This is a generic overview of testing jobs on the staging server
> Add some testing documentation

- app/models/web_staff/staff_member.rb
- spec/models/web_staff/staff_directory_generator_spec.rb
- spec/models/web_staff/staff_member_spec.rb
> Add phone number filter

- config/deploy/staging.rb
- config/schedule.rb
- lib/tasks/lib_jobs.rake
Closes: #385
Testing on staging:
```bash
deploy@lib-jobs-staging1:~$ touch -mt 202210030000 /tmp/test.txt
deploy@lib-jobs-staging1:/opt/lib-jobs/current$ bundle exec rake lib_jobs:clear_out_temp_directories
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.12.1 framework=ruby level=1 pid=6341
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.12.1 framework=ruby level=1 pid=6341
Deleting files older than 1 week in /tmp
Deleting file: /tmp/test.txt, last updated: 2022-10-03 00:00:00 +0000
Deleting file: /tmp/bash.deb.sh, last updated: 2022-06-24 13:41:38 +0000
Deleting files older than 1 week in /opt/lib-jobs/shared/
```
> Add rake task to delete old files

- app/models/alma_pod_records/alma_pod_job.rb
- app/models/alma_pod_records/alma_pod_sender.rb
- app/models/marc_collection.rb
- config/config.yml
- config/schedule.rb
- lib/tasks/lib_jobs.rake
- spec/models/alma_pod_records/alma_pod_job_spec.rb
- spec/models/alma_pod_records/alma_pod_sender_spec.rb
- spec/models/marc_collection_spec.rb
> Compress pod data

- app/models/web_staff/staff_member.rb
- spec/models/web_staff/staff_directory_generator_spec.rb
- spec/models/web_staff/staff_member_spec.rb
> i412: better handling of staff without phone numbers

- Gemfile
- Gemfile.lock
- app/controllers/library_events_controller.rb
- app/models/web_events/event.rb
- app/models/web_events/events_feed_generator.rb
- app/models/web_events/libcal_url.rb
- config/config.yml
- config/routes.rb
- config/schedule.rb
- docs/web_events/README.md
- lib/tasks/lib_jobs.rake
- spec/fixtures/files/libcal_events.ics
- spec/models/web_events/event_spec.rb
- spec/models/web_events/events_feed_generator_spec.rb
- spec/models/web_events/libcal_url_spec.rb
Closes #415 
Co-authored-by: Robert-Anthony Lee-Faison <leefaisonr@users.noreply.github.com>
> Add new lib-job that converts ical to csv

- app/models/web_events/events_feed_generator.rb
- spec/models/web_events/events_feed_generator_spec.rb
> i419: Record the correct report_time for EventsFeed

- config/schedule.rb
> Only run compressed pod job on prod

- app/models/access_token.rb
- app/models/web_database_list/libguides_assets_feed.rb
- config/config.yml
- docs/web_database_list/README.md
- spec/models/access_token_spec.rb
- spec/models/web_database_list/libguides_assets_feed.spec
Closes #447
Sibling PR: https://github.com/pulibrary/princeton_ansible/pull/3660
On the staging server, you can retrieve the JSON from Libguides with
```
$ bundle exec rails c
irb(main):001:0> WebDatabaseList::LibguidesAssetsFeed.new.fetch
```
> i447 assets feed

- .circleci/config.yml
- .tool-versions
Sibling PR: https://github.com/pulibrary/princeton_ansible/pull/3665
> Upgrade node to 16

- app/controllers/library_databases_controller.rb
- app/models/lib_job.rb
- app/models/web_database_list/database.rb
- app/models/web_database_list/databases_feed.rb
- app/models/web_events/events_feed_generator.rb
- config/routes.rb
- config/schedule.rb
- lib/tasks/lib_jobs.rake
- spec/fixtures/files/libguides_databases.json
- spec/models/web_database_list/database_spec.rb
- spec/models/web_database_list/databases_feed_spec.rb
Closes #442 
You can check the CSV output at https://lib-jobs-staging.princeton.edu/library-databases.csv
> i442 libguides database csv

- Gemfile
- Gemfile.lock
- config/environments/production.rb
- config/environments/staging.rb
> i458: prefer terser over uglifier

- app/models/csv_validator.rb
- app/models/web_staff/hr_staff_report.rb
- spec/models/web_staff/hr_staff_report_spec.rb
> i466 closed file io

- app/models/web_staff/staff_member.rb
- config/staff_directory.yml
- docs/web_staff/README.md
- spec/models/web_staff/hr_staff_report_spec.rb
- spec/models/web_staff/staff_directory_difference_spec.rb
- spec/models/web_staff/staff_directory_generator_spec.rb
> i460: use Active Library Staff report

- Gemfile.lock
- app/models/alma_pod_records/alma_pod_job.rb
- app/models/alma_pod_records/alma_pod_sender.rb
- config/config.yml
- config/schedule.rb
- db/schema.rb
- lib/tasks/lib_jobs.rake
- spec/models/alma_pod_records/alma_pod_job_spec.rb
- spec/models/alma_pod_records/alma_pod_sender_spec.rb
> Only send compressed data to POD

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- README.md
> Remove TinyTDS

- app/models/web_database_list/databases_feed.rb
- spec/models/web_database_list/databases_feed_spec.rb
> Skip databases without a friendly_url

- config/scsb_s3.yml
> Add config for scsb s3 connection

- config/scsb_s3.yml
> Remove unneeded scsb vars

- config/schedule.rb
> Change time of voucher_feed job

- app/models/alma_sftp.rb
- spec/models/alma_sftp_spec.rb
> Add SFTP connection retries

- app/models/alma_renew/renew_job.rb
- spec/models/alma_renew/renew_job_spec.rb
> Retry when there is a renewal error

- app/models/alma_people/alma_xml_person.rb
- spec/models/alma_people/alma_xml_person_spec.rb
> Remove duplicate 'Person' from message

- Gemfile
- Gemfile.lock
- app/assets/javascripts/data_sets.coffee
- db/schema.rb
closes #523 
Remove spring, spring-watcher,coffee-rails,sqlite3
keep gem 'matrix'
> Remove gems

- Gemfile
- Gemfile.lock
- app/views/data_sets/index.html.erb
- app/views/layouts/application.html.erb
- spec/rails_helper.rb
- spec/system/accessibility_spec.rb
closes #472 
Add axe-core library, add accessibility spec, fix lang accessibility.
> Accessibility spec

- Gemfile
- Gemfile.lock
- When starting application in development, ran into error "undefined method 'wait_for_state'"
- Referenced in https://github.com/rails/rails/issues/48620 and fix was upgrading listen gem, which resolved issue
> Upgrade listen gem

- docs/alma_renew/README.md
> Update Alma renew documentation for mermaid chart accessibility

- docs/web_database_list/README.md
> Update web database list documentation for mermaid chart accessibility

- docs/peoplesoft_voucher/README.md
> Update Peoplesoft voucher documentation for mermaid chart accessibility

- docs/peoplesoft_bursar/README.md
> Update PeopleSoft Bursar documentation for mermaid chart accessibility

- docs/alma_people/README.md
> Update Alma People documentation for mermaid chart accessibility

- docs/alma_pod_records/README.md
> Update Alma POD Records documentation for mermaid chart accessibility

- docs/web_events/README.md
> Update web events documentation for mermaid chart accessibility

- .circleci/config.yml
- spec/support/system_specs.rb
Thanks to @carolyncole and @hackartisan!
> Use new CircleCI orb to fix bug

- Gemfile
No substantive changes to gemfile, only alpha and consistent use of single quotes (Reviewer: if you'd rather consistent double quotes that's fine with me - I'd just rather one or the other, not scattershot)
> Alpha gemfile for easier to read dependencies

- docs/alma_normalization_process/readme.md
> Add mermaid chart for alma normalization process

- spec/system/accessibility_spec.rb
> Remove test exception

- app/models/oclc/newly_cataloged_file.rb
- app/models/oclc/newly_cataloged_job.rb
- app/models/oclc/record.rb
- app/models/oclc/selector_csv.rb
- docs/oclc_newly_cataloged/readme.md
- lib/tasks/lib_jobs.rake
- spec/models/oclc/newly_cataloged_file_spec.rb
- spec/models/oclc/newly_cataloged_job_spec.rb
- spec/models/oclc/record_spec.rb
- spec/models/oclc/selector_csv_spec.rb
- Adds the wrapper job and population of CSV file. 
- Adds mermaid diagram for process
- Adds rake task to run both full job and to run single files at a time. 
Connected to #234
> I234 newly cataloged file and job

- app/models/oclc/data_sync_exception_file.rb
- app/models/oclc/data_sync_exception_job.rb
- config/oclc_sftp.yml
- spec/fixtures/oclc/PUL-PUL.1012676.IN.BIB.D20230712.T115732756.1012676.pul.non-pcc_27837389230006421_new.mrc_1.BibExceptionReport.txt
- spec/models/oclc/data_sync_exception_file_spec.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
> I580 marc coll for exceptions

- app/models/oclc/data_sync_exception_job.rb
- app/models/oclc/newly_cataloged_job.rb
- app/models/oclc/report_downloader.rb
- config/oclc_sftp.yml
- spec/models/oclc/data_sync_exception_job_spec.rb
- spec/models/oclc/report_downloader_spec.rb
Refactored the two existing jobs that download files from the alma sftp server to use a reusable class that can also be used for the remaining job that will be implemented.
> Refactored SFTP downloads into report downloader

- app/models/oclc/data_sync_exception_file.rb
- app/models/oclc/data_sync_exception_job.rb
- config/oclc_sftp.yml
- lib/tasks/lib_jobs.rake
- spec/models/oclc/data_sync_exception_file_spec.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
Closes #581
@mzelesky has confirmed that the records generated using this job match the ones generated using the original scripts.
> I581 put data sync exceptions on sftp

- docs/data_sync_exceptions/readme.md
> Create Mermaid diagram for BibException report

- app/models/oclc/data_sync_exception_job.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
> Add data to DataSyncExceptionJob

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- app/models/aspace_svn/get_eads_job.rb
- config/aspace.yml
- config/brakeman.ignore
- config/deploy.rb
- spec/models/aspace_svn/get_eads_job_spec.rb
> send EAD exports from ASpace to SVN

- docs/data_sync_processing/readme.md
> Created mermaid chart for data sync processing

- app/models/oclc/data_sync_exception_job.rb
- app/models/oclc/data_sync_processing_file.rb
- app/models/oclc/data_sync_processing_job.rb
- app/models/oclc/report_uploader.rb
- config/oclc_sftp.yml
- lib/tasks/lib_jobs.rake
- spec/models/alma_submit_collection/alma_recap_file_list_spec.rb
- spec/models/alma_submit_collection/alma_submit_collection_job_spec.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
- spec/models/oclc/data_sync_processing_file_spec.rb
- spec/models/oclc/data_sync_processing_job_spec.rb
- spec/models/oclc/report_uploader_spec.rb
Tested successfully from development environment, pushing to lib-sftp-staging1. I had to change the time-span of files it was looking for in testing, since the newest files are from 8/7/2023 (today is 8/15/2023, so they're from more than a week ago). 
Connected to #585
> Upload DataSyncProcessed files to alma sftp

- app/models/aspace_svn/get_eads_job.rb
- spec/models/aspace_svn/get_eads_job_spec.rb
> Preventing exception from crashing the job

- config/schedule.rb
(https://crontab.guru/#0_6_1-7_*_*/6 'At 06:00 on every day-of-month from 1 through 7 if it's on every 6th day-of-week')
> Send on first Saturday of the month 

- app/models/alma_submit_collection/alma_api.rb
- app/models/alma_submit_collection/marc_location_field_factory.rb
- config/config.yml
- spec/models/alma_bib_norm/alma_bib_norm_spec.rb
> I624 frozen string

- .circleci/config.yml
Addresses this issue: https://github.com/CircleCI-Public/browser-tools-orb/issues/90
> Bump circleci browser-tools orb version

- app/models/alma_renew/item.rb
> Add new affliate status. 

- .circleci/config.yml
> Use node 18 in circleci

- .circleci/config.yml
- config/deploy/production.rb
- package.json
- yarn.lock
part of #https://github.com/pulibrary/princeton_ansible/issues/3476
> upgrade nodejs and jammy

- config/deploy.rb
- config/deploy/production.rb
- config/schedule.rb
> set lib-jobs-prod2 to cron_prod2 whenever role

- config/schedule.rb
> Mixed incorrect times in the notes for the schedule

- .circleci/config.yml
> Use latest browser-tools orb

- config/initializers/devise.rb
- spec/rails_helper.rb
Address deprecation warnings for Rails 7.1
> Address deprecation warnings

- Gemfile.lock
- app/models/oclc/record.rb
- config/newly_cataloged.yml
- spec/models/oclc/newly_cataloged_file_spec.rb
- spec/models/oclc/newly_cataloged_job_spec.rb
- spec/models/oclc/record_spec.rb
- Adds configuration for new selectors
- Handles variations to config correctly
Example files have been sent to all selectors, positive feedback from the two we have heard back from.
> Add all selectors to config

- app/models/alma_submit_collection/marc_record.rb
- app/models/alma_submit_collection/marc_s3_writer.rb
- app/models/marc_collection.rb
Something that @christinach, @maxkadel, and I added to make it easier to see the job's process in the memory profiler.
> Add more logging to SubmitCollection job

- config/lc_call_slips.yml
> Update config - add languages to exclude

- app/models/marc_collection_document_callbacks.rb
> No need for a separate assignment step when writing xml attributes to Tempfile

- app/models/oclc/lc_call_slips/record.rb
- spec/models/oclc/lc_call_slips/record_spec.rb
> Use case insensitive matching

- app/models/alma_people/alma_person_feed.rb
- config/features.rb
- spec/models/alma_people/alma_person_feed_spec.rb
> Added new call to generate ineligible user file

- config/lc_call_slips.yml
> [lc_call_slips] Remove HB classes for Donatiello

- config/alma_sftp.yml
- config/peoplesoft.yml
- spec/models/alma_fund_adjustment/adjustment_check_spec.rb
- spec/models/alma_fund_adjustment/file_converter_spec.rb
- spec/models/alma_fund_adjustment/file_transfer_spec.rb
- spec/models/alma_invoice_status/file_converter_spec.rb
- spec/models/alma_people/alma_person_feed_spec.rb
- spec/models/report_uploader_spec.rb
> Use different directories in tests to ensure inheritance is working as expected

- app/models/report_uploader.rb
- spec/models/report_uploader_spec.rb
Connected to #743  - some uploads expect to mark a file as processed after a successful upload.
> I743 mark file as processed

- app/models/oclc/data_sync_exception_job.rb
- app/models/report_uploader.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
- spec/models/report_uploader_spec.rb
Rescue from upload errors and log.
> Add more error handling for sftp upload

- app/models/alma_renew/alma_renew_list.rb
Use foreach method for csv parsing
> Factor out process method

- docs/gobi/readme.md
> Added documentation and a diagram for gobi job

- app/models/alma_submit_collection/alma_recap_file_list.rb
Having trouble testing this, but it seems fairly straightforward.
Closes #765
> Skip deletes in the glob

- app/models/alma_people/alma_person_feed.rb
- app/models/alma_people/alma_xml_person.rb
- spec/models/alma_people/alma_person_feed_spec.rb
- spec/models/alma_people/alma_xml_person_spec.rb
> [i769] Don't include retirees in list of ineligible patrons for Alma

- app/models/alma_submit_collection/alma_recap_file_list.rb
This reverts commit ddc019e2cc85aabcfa517d239a2db3297b69f0e5.
Connected to #779
> Revert "Skip deletes in the glob"

- app/controllers/application_controller.rb
related to https://github.com/pulibrary/lux-design-system/issues/231
> Activate Lux menu bar method post 

- app/models/air_table_staff/csv_builder.rb
- app/models/air_table_staff/staff_directory_mapping.rb
- spec/fixtures/files/air_table/records_no_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
- spec/models/air_table_staff/staff_list_job_spec.rb
Connected to #804
Deployed to staging, works.
> Add scheduler link to staff csv

- app/models/gobi/isbn_report_job.rb
Deployed and tested on staging.
Closes #809
> Require CSV

- app/models/gobi/isbn_file.rb
- app/models/oclc/lc_call_slips/all_relevant_file.rb
- app/models/oclc/lc_call_slips/all_relevant_job.rb
- app/models/oclc/lc_call_slips/selector_csv.rb
- app/models/oclc/lc_call_slips/selector_file.rb
> Consistently include csv when used

- app/models/air_table_staff/staff_directory_mapping.rb
- spec/fixtures/files/air_table/records_no_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
- spec/models/air_table_staff/staff_list_job_spec.rb
> 815 add new fields airtable

- app/models/air_table_staff/record_list.rb
- spec/fixtures/files/air_table/records_no_offset_empty_records.json
- spec/models/air_table_staff/record_list_spec.rb
- spec/support/stub_airtable.rb
> 805 ignore empty rows

- .circleci/config.yml
- bearer.ignore
- bearer.yml
Connected to https://github.com/pulibrary/dacs_handbook/issues/238
> Add bearer to CI

- .semgrepignore
- Gemfile
- Gemfile.lock
- config/initializers/health_monitor.rb
- config/routes.rb
- spec/requests/health_check_spec.rb
> Add health check

- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/initializers/health_monitor.rb
- **pin version of health-monitor**
- **add two loadbalancer caps**
closes #859
> new loadbalancer cap tasks

- config/lc_call_slips.yml
> Send slips that were going to Donatiello to Bordelon

- config/initializers/health_monitor.rb
> Remove honeybadger alert for health check failures

- .circleci/config.yml
- app/models/user.rb
- bearer.yml
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- db/migrate/20250212181445_encrypt_user_emails.rb
- db/schema.rb
- spec/models/user_spec.rb
> Migrate to encrypted emails

- .circleci/config.yml
> [#876] CircleCi continuous deployment config

- Capfile
- app/models/aspace_version_control/get_eads_job.rb
- app/models/aspace_version_control/svn.rb
- config/aspace.yml
- config/brakeman.ignore
- lib/tasks/lib_jobs.rake
- spec/models/aspace_version_control/get_eads_job_spec.rb
- spec/models/aspace_version_control/svn_spec.rb
> Separate SVN from other EAD manipulation

- .circleci/config.yml
- README.md
> Add coveralls to CI

- app/models/alma_submit_collection/marc_item_field_factory.rb
> update retention reasons

- docs/alma_normalization_process/readme.md
Thanks @mzelesky for the information!
> [bib-norm job] Add a note that this can be kicked off at any time

- config/schedule.rb
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
> Run once monthly

- app/models/alma_submit_collection/marc_item_field_factory.rb
> add ReCAPFrenchImprints retention reason

- app/models/aspace_version_control/get_eads_job.rb
- app/models/aspace_version_control/git_lab.rb
- spec/models/aspace_version_control/get_eads_job_spec.rb
- spec/models/aspace_version_control/git_lab_spec.rb
> Checkout files before pull
