pulibrary/lib_jobs

- Gemfile
- Gemfile.lock
- config/deploy.rb
These changes were necessary in order to ensure that LibJobs may be deployed from Slack using the pulbot.
> Updating Capistrano config. options to support deployments from the pulbot

- config/schedule.rb
avoids `/bin/bash: bundle: command not found` error
> Adding path to crontab

- spec/system/absolute_id_system_spec.rb
There's a bunch of uncovered edge cases, but I don't really understand
where they'd come about. I wonder if we can just remove this feature
entirely?
> Add a little XML coverage.

- app/jobs/absolute_ids/session_synchronize_job.rb
- spec/jobs/absolute_ids/session_synchronize_job_spec.rb
AbIDs are not unique across all of ASpace, they're only unique across
streams. The application enforces that, so we can just remove ASpace
check.
> Remove uniqueness requirement.

- app/models/alma_xml_invoice_list.rb
- spec/models/alma_xml_invoice_list_spec.rb
- spec/models/voucher_feed_spec.rb
Based on feedback from testing, they would prefer not to have the header line in the csv.
> Removing header line from onbase report

- app/jobs/absolute_ids/create_model_from_aspace_job.rb
- spec/requests/absolute_ids/session_request_spec.rb
- spec/requests/barcodes/session_request_spec.rb
It was unreliable before, this guaruntees that the EAD-ID is passed
through from the form.
> Pass ID, don't pull it from resource.

- Gemfile
- Gemfile.lock
We had to maintain a local fork of this gem for awhile, but the fix we
needed has since been incorporated upstream.
> Use upstream archivesspace-client

- Gemfile
- Gemfile.lock
- app/mailers/finance_mailer.rb
- config/application.rb
- config/config.yml
- db/seeds.rb
fixes #213
Also removed unused configuration and database seeding that was left over from when Absolute Ids was part of lib_jobs
>  Allowing finance email addresses to be configured

- app/models/peoplesoft_voucher/alma_xml_fund_list.rb
- app/models/peoplesoft_voucher/alma_xml_invoice.rb
- app/models/peoplesoft_voucher/alma_xml_invoice_list.rb
- app/models/peoplesoft_voucher/finance_xml_invoice.rb
- spec/fixtures/finance_invoice.xml
- spec/fixtures/invoice_export_202118300518.xml
We did not have an example with multiple funds for one transaction.  Change the example to have multiple and change the output
> Changing how the distribution lines are numbered

- app/models/peoplesoft_voucher/alma_xml_invoice.rb
- spec/fixtures/finance_invoice.xml
- spec/models/peoplesoft_voucher/alma_xml_invoice_list_spec.rb
- spec/models/peoplesoft_voucher/alma_xml_invoice_spec.rb
- spec/models/peoplesoft_voucher/voucher_feed_spec.rb
Change to base 36 instead of base 10 so we can include the entire alma id number
We originally specified base 32, but I realized we could include all the zeros if we did base 36.
fixes #221
> Updating the unique identifier algorithm for voucher ids

- yarn.lock
Fixes a dependabot alert that was unable to automatically generate a PR
> Bump node-fetch version

- app/models/alma_pod_records/alma_pod_file_list.rb
- app/models/alma_pod_records/alma_pod_job.rb
- app/models/marc_collection.rb
- config/pod.yml
- spec/models/alma_pod_records/alma_pod_job_spec.rb
- spec/models/marc_collection_spec.rb
Previously, the pod rake task took about 4GB of RAM to process a 1.1GB MARCXML file.  With this PR, it takes about 2GB of RAM.
> Use less memory for pod

- config/schedule.rb
Per @mzelesky. When large groups of records  in this set are touched the previous window will come up before Alma has completed the process.
> Add more padding on POD processing time

- app/models/peoplesoft_bursar/credit_report.rb
- app/models/peoplesoft_bursar/fine_report.rb
- app/models/peoplesoft_bursar/job.rb
- app/models/peoplesoft_bursar/report.rb
- spec/mailers/finance_mailer_spec.rb
- spec/models/peoplesoft_bursar/job_spec.rb
Removes extra generic line from the email
fixes #319
> Allowing type in mail to be credit or payment

- docs/peoplesoft_bursar/README.md
- docs/web_staff/README.md
This is not completed work.  The fines document in the bursar is the only agreed upon diagram
Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
Co-authored-by: Mark Zelesky <mzelesky@users.noreply.github.com>
> Adding documents for web-staff and bursar

- config/config.yml
- Having ENV.fetch without default makes it so you can't run individual tests
> Make it so we can run single tests

- app/mailers/alma_people_mailer.rb
- app/models/alma_people/alma_person_feed.rb
- app/models/alma_people/alma_xml_person.rb
- app/views/alma_people_mailer/error_notification.html.erb
- app/views/alma_people_mailer/error_notification.text.erb
- config/config.yml
- docs/alma_people/README.md
- spec/mailers/finance_mailer_spec.rb
- spec/mailers/previews/alma_people_preview.rb
- spec/mailers/transaction_error_spec.rb
- spec/models/alma_people/alma_person_feed_spec.rb
- spec/models/alma_people/alma_xml_person_spec.rb
closes #355 
We will need to add the `PEOPLE_ERROR_NOTIFICATION_RECIPIENTS` envvar to the servers first, containing a comma-separated list of stakeholders to receive these messages.
> i355: Send an email report on nil expiration dates

- config/environments/production.rb
closes #320 
Raise delivery errors, so that Honeybadger can inform us when an email fails to send.
> i320: Turn on ActionMailer delivery errors

- .circleci/config.yml
- Gemfile.lock
Connected to https://github.com/pulibrary/princeton_ansible/issues/3112 - need to update bundler in order to use ruby_s role (according to the readme)
> Update bundler for ruby_s ansible role

- spec/models/web_staff/staff_member_spec.rb
closes #389 -  the desired behavior is already in place, and is exercised in an integration test.  This just adds some additional confirmation in a unit test.
> i389: add unit test to confirm that Register Title is used

- config/schedule.rb
Apparently I got it wrong and put it at 3 am UTC before, when we wanted 3 am EST, this fixes that.
Closes #493
> Move voucher_feed to 3 am est

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/peoplesoft_voucher/voucher_feed.rb
- app/models/user.rb
- config/application.rb
- config/environments/development.rb
- config/environments/test.rb
- config/features.rb
- config/routes.rb
- db/migrate/20230516155655_create_features.rb
- db/schema.rb
- docs/peoplesoft_voucher/README.md
- spec/models/peoplesoft_voucher/voucher_feed_spec.rb
- spec/models/user_spec.rb
- spec/support/devise.rb
- spec/system/header_spec.rb
closes #371 
To manually test the permissions on the flipflop dashboard:
- As `deploy@lib-jobs-staging1`, edit app_configs/lib-jobs to remove your netid from the `LIB_JOBS_ADMIN_NETIDS` line
- As `pulsys@lib-jobs-staging1`, run `sudo systemctl restart nginx`
- In your browser, confirm that you can no longer access https://lib-jobs-staging.princeton.edu/features
> i371: add a feature flipper for Voucher Feed job

- app/models/alma_fund_adjustment/adjustment_check.rb
- app/models/alma_invoice_status/file_converter.rb
- config/features.rb
- spec/models/alma_fund_adjustment/adjustment_check_spec.rb
- spec/models/alma_invoice_status/file_converter_spec.rb
Resolves #514 
There are two outstanding accessibility issues I was unable to resolve directly, as the feature page is generated and not under our control.
1. The enabled badge's contrast isn't high enough
2. When navigating using voiceover you can turn the features on and off, but it's not clear what feature you are changing. 
Creating issues to address these in the Flipflop gem.
> Added feature flipper for alma jobs

- Gemfile
- Gemfile.lock
This resolves an issue where we couldn't call AlmaSftp#run from the rails console
> Upgrade sftp-related gems

- app/models/oclc/data_sync_exception_job.rb
- config/oclc_sftp.yml
- spec/fixtures/oclc/PUL-PUL.1012676.IN.BIB.D20230712.T115712289.1012676.pul.non-pcc_27837389230006421_new.mrc_2.BibExceptionReport.txt
- spec/fixtures/oclc/PUL-PUL.1012676.IN.BIB.D20230712.T115732756.1012676.pul.non-pcc_27837389230006421_new.mrc_1.BibExceptionReport.txt
- spec/models/oclc/data_sync_exception_job_spec.rb
Note that this writes the files from OCLC to temp files that can be passed along to the next class for processing, and will then be cleaned up by the ruby garbage collection process. 
Closes #579
> Download OCLC exception files

- app/mailers/newly_cataloged_mailer.rb
- app/models/oclc/newly_cataloged_job.rb
- app/models/oclc/selector.rb
- app/views/newly_cataloged_mailer/report.html.erb
- app/views/newly_cataloged_mailer/report.text.erb
- config/newly_cataloged.yml
- config/schedule.rb
- spec/mailers/newly_cataloged_mailer_spec.rb
- spec/models/oclc/newly_cataloged_job_spec.rb
- spec/models/oclc/selector_spec.rb
Emails CSVs of books that have recently been cataloged by the Library of Congress to selectors for whom those books are relevant. Creates the CSVs and emails them weekly.
Connected to #564
> I564 email newly cataloged csvs

- app/models/oclc/newly_cataloged_job.rb
- spec/models/oclc/newly_cataloged_job_spec.rb
Did not add a data_file, because the job creates separate data files for each selector. Currently just records the list of files that have been sent to selectors. These files will be deleted after a week, since they are not needed long term (they're included in the file cleanup job).
Connected to #604
> Add data to data_set for NewlyCatalogedJob

- Gemfile
- Gemfile.lock
- spec/support/system_specs.rb
- Failing in CI because of Chromedriver / Chrome mismatch
Based on https://github.com/pulibrary/orangelight/pull/3658
> Use only selenium-webdriver, not webdrivers

- config/schedule.rb
Should not be merged until `BibProcessingJob` work has been merged.
Blocked by #585
Closes #597
> Add Whenever jobs to schedule / cron

- Gemfile.lock
- Not sure how the tag got in there, but it is not the tag we want
1. Removed whole stanza in Gemfile.lock for Flipflop
2. Ran `bundle install` locally
3. Re-generated Gemfile.lock did not include the `tag: v0.9.0` line
> Update Gemfile.lock to remove tag

- config/schedule.rb
OIT advises they needed to change the report run time to 8 a.m. Updating schedule.
> Update Time Staff Report Is Processed

- app/models/web_events/events_feed_generator.rb
Closes https://github.com/pulibrary/lib_jobs/security/code-scanning/1
This URL is not user-controlled (it's generated based on the yaml configs), so I don't consider us vulnerable at the moment.  This is more a matter of best practice.
> Prefer URI().open over URI.open()

- .circleci/config.yml
- Gemfile.lock
This is not required for deployment to work, but I like keeping the application bundler aligned with the one in production.
Had to upgrade bundler to resolve #663
See also pulibrary/princeton_ansible#4685
> Upgrade bundler to match production

- app/models/alma_submit_collection/alma_api.rb
- app/models/alma_submit_collection/marc_file_processor.rb
- app/models/marc_collection.rb
- app/models/marc_collection_document_callbacks.rb
- spec/models/alma_pod_records/alma_pod_job_spec.rb
- spec/models/marc_collection_document_callbacks_spec.rb
This patch replaces various occurences where huge MARC files are read into memory as Strings or StringIOs.  Instead, it uses:
* TempFiles on disk
* A SAX parser that allows us to read XML files into memory one element at a time, rather than all at once.
* Nokogiri in one case where we were using ReXML
Related to #695 
I tried this out on staging, and also the main branch, with 4 files:
| branch | peak memory consumption | memory consumption pattern | time |
| --- | --- | --- | --- |
| this one | 0.4 GB | steady during the whole run | 4 minutes 33 seconds |
| main | 1.2 GB | growing at a regular pace during the whole run | 4 minutes 7 seconds |
For what it's worth, there are 475 files that need to be processed in prod.
> Allow large files to process without running out of memory

- app/models/alma_submit_collection/alma_submit_collection_job.rb
- app/models/alma_submit_collection/marc_file_processor.rb
- app/models/alma_submit_collection/marc_s3_writer.rb
- spec/models/alma_submit_collection/marc_file_processor_spec.rb
- spec/models/alma_submit_collection/marc_s3_writer_spec.rb
Previously, we created 2 Aws::S3::Client objects for each file on the SFTP server: one for host/constitutent records, the other for bound-with records.  As part of its initialization, Aws::S3::Client slurps a 800 KB JSON file into memory, which it uses to determine the endpoint it wants to use.  800 KB isn't too bad, but if we add two copies to memory 4000 times, it leads to some serious memory pressure.
related to #695
> Only initialize the S3 Connection once

- app/models/marc_collection_document_callbacks.rb
- spec/models/marc_collection_document_callbacks_spec.rb
This causes us to allocate slightly less memory.  These strings are not retained for very long, but since this method is called so many times, it does result in more work for the garbage collector.
part of #695
> Use encode! rather than encode to modify string in place

- app/models/alma_submit_collection/marc_s3_writer.rb
> Compress MARC records a few bytes at a time, rather than reading the entire uncompressed file into memory

- app/models/tarball.rb
- spec/models/alma_submit_collection/alma_recap_file_list_spec.rb
Part of #695 
This branch mysteriously allocates slightly more memory, but retains less memory overall.
> Use Tempfiles, rather than StringIO, when decompressing a tarball

- app/models/gobi_sftp.rb
- app/models/sftp.rb
- config/gobi_sftp.yml
- spec/models/alma_sftp_spec.rb
- spec/models/gobi_sftp_spec.rb
- spec/models/oclc_sftp_spec.rb
- spec/models/sftp_spec.rb
- spec/support/sftp_shared_examples.rb
- The Gobi sftp server does not have modern algorithms available to authenticate with, so we have to append all supported algorithms, some of which are less secure
- Default to not appending the less secure algorithms
- Refactor SFTP specs to use shared examples when appropriate, add an SFTP spec for parent class
- Update Gobi sftp config, make sure they work for test and dev as well
Connected to #679
> Allow less secure algorithms for some SFTP classes

- app/models/oclc/lc_call_slips/record.rb
- app/models/oclc/lc_call_slips/selector.rb
- config/lc_call_slips.yml
- spec/models/oclc/lc_call_slips/all_relevant_job_spec.rb
- spec/models/oclc/lc_call_slips/record_spec.rb
- spec/models/oclc/lc_call_slips/selector_spec.rb
Basically right now this is an on-off toggle for all US / UK / Canada locations
Connected to #703
> Make excluding US / UK / Canada pub locations configurable

- app/models/oclc/lc_call_slips/keyword_field.rb
- app/models/oclc/lc_call_slips/record.rb
- app/models/oclc/lc_call_slips/selector.rb
- spec/models/oclc/lc_call_slips/keyword_field_spec.rb
- spec/models/oclc/lc_call_slips/record_spec.rb
Closes #678 
@maxkadel and I checked this by running the `lib_jobs:process_newly_cataloged_records` on main and on a branch with this commit and some testing keywords.  We downloaded the CSVs from mailcatcher and compared them.  The keywords did add a few records to the CSVs, and searching for the OCLC records in [firstsearch](https://libguides.princeton.edu/resource/4165) helped to confirm that those new records did in fact contain the keywords.
> Add keyword configuration option to OCLC newly added

- README.md
- docs/lc_call_slips/testing_on_staging.md
Also, fix the link and formatting in the README's mailcatcher section.
> Add documentation for testing lc call slips on staging

- app/models/alma_people/alma_person_feed.rb
- app/models/oclc/data_sync_exception_job.rb
Connected to #743  
- the DataSyncExceptionJob wasn't actually using its `upload_files_to_alma_sftp` method, it was already using the ReportUploader.
- refactor the AlmaPersonFeed to use the ReportUploader
> Refactor uploader for datasync exception and alma person feed

- config/lc_call_slips.yml
closes #747 
I tested this on staging -- for this week, at least, the keywords don't add any additional titles that weren't already identified by call number or subject.
> [lc call slips] Add keywords to David Hollander's config

- app/models/oclc/lc_call_slips/keyword_field.rb
- spec/models/oclc/lc_call_slips/keyword_field_spec.rb
> [lc call slips] ignore trailing punctuation when keyword matching

- app/models/alma_renew/alma_renew_list.rb
- spec/models/alma_renew/alma_renew_list_spec.rb
- spec/models/alma_renew/renew_job_spec.rb
- spec/models/gobi/isbn_report_job_spec.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
- spec/models/oclc/data_sync_processing_job_spec.rb
- spec/models/oclc/lc_call_slips/all_relevant_job_spec.rb
- spec/models/oclc/lc_call_slips/selector_job_spec.rb
- spec/models/report_downloader_spec.rb
- This is an incremental step toward using the ReportDownloader
- It may help with memory issues on the LibJobs boxes
> Refactor AlmaRenewList to use a tempfile rather than datastream

- app/models/alma_submit_collection/alma_recap_file_list.rb
- config/alma_sftp.yml
- config/features.rb
- docs/alma_submitcollection/README.md
- spec/models/alma_submit_collection/alma_recap_file_list_spec.rb
Connected to #765
Connected to #763
> Introduce metering for submit collection

- app/models/oclc/lc_call_slips/selector.rb
- config/application.rb
- docs/lc_call_slips/testing_on_staging.md
- spec/models/oclc/lc_call_slips/all_relevant_job_spec.rb
- spec/models/oclc/lc_call_slips/config_spec.rb
- spec/models/oclc/lc_call_slips/record_spec.rb
- spec/models/oclc/lc_call_slips/selector_csv_spec.rb
- spec/models/oclc/lc_call_slips/selector_file_spec.rb
- spec/models/oclc/lc_call_slips/selector_job_spec.rb
- spec/models/oclc/lc_call_slips/selector_spec.rb
- Refactors so we can test against production configuration when we want to, and test configuration by default
- Adds a validation method to Selectors model, currently only used in config test
- This will allow us to be more confident that our production configuration doesn't break anything
Closes #775
> I775 lc call slips config check

- app/models/oclc/data_sync_exception_file.rb
- app/models/report_downloader.rb
- app/models/report_uploader.rb
- spec/fixtures/oclc/PUL-PUL.1012676.IN.BIB.D20240529.T011306010.1012676.pul.non-pcc_37850317700006421_new.mrc_247.BibExceptionReport.txt
- spec/models/oclc/data_sync_exception_file_spec.rb
- spec/models/oclc/data_sync_exception_job_spec.rb
- spec/models/report_uploader_spec.rb
Does not list working_file that never had data written to it
- When there were no valid errors, no file was getting created, which meant we would try to upload a non-existent file.
- Add some more logging for future debugging
Closes https://github.com/pulibrary/lib_jobs/issues/643
> Does not list working_file that never had data written to it

- app/models/air_table_staff/csv_builder.rb
- app/models/air_table_staff/json_value_extractor.rb
- app/models/air_table_staff/record_list.rb
- app/models/air_table_staff/staff_directory_mapping.rb
- app/models/air_table_staff/staff_directory_person.rb
- config/config.yml
- spec/fixtures/files/air_table/records_no_offset.json
- spec/fixtures/files/air_table/records_with_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/json_value_extractor_spec.rb
- spec/models/air_table_staff/record_list_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
These classes work together to download data from airtable and compile a CSV staff list. It is not yet a "job", but if you have an airtable personal access token with the appropriate permissions, the following should work in `rails c`:
```
AirTableStaff::CSVBuilder.new.to_csv
```
Part of #697
> Basic functionality for airtable staff list

- app/controllers/staff_directory_controller.rb
- app/models/air_table_staff/staff_list_job.rb
- config/features.rb
- config/routes.rb
- docs/air_table_staff/README.md
- spec/models/air_table_staff/staff_list_job_spec.rb
closes #697
It is currently deployed to staging, and you can access it at https://lib-jobs-staging.princeton.edu/pul-staff-report.csv
It is behind a feature flipper, which I turned on in staging
> Add an airtable staff list job and URL

- app/models/air_table_staff/staff_directory_mapping.rb
- spec/fixtures/files/air_table/records_no_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
- spec/models/air_table_staff/staff_list_job_spec.rb
> Add Title to staff csv

- docs/air_table_staff/README.md
Taken from @kevinreiss' ticket #697
> [airtable-staff-list] Add links to airtable UI and API docs

- app/models/air_table_staff/staff_directory_mapping.rb
- spec/fixtures/files/air_table/records_no_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
- spec/models/air_table_staff/staff_list_job_spec.rb
closes #799 
The CSV column headers for the new fields are `websiteUrl`, `bios`, and `expertise`, to keep consistent capitalization with the other column headers.
> [airtable staff directory] Add websiteUrl, bios, and expertise fields

- README.md
Postgres is provided by lando, and we don't currently use python in this project.
> Remove old documentation from README

- app/models/air_table_staff/json_value_extractor.rb
- app/models/air_table_staff/record_list.rb
- app/models/air_table_staff/staff_directory_mapping.rb
- config/config.yml
- spec/fixtures/files/air_table/records_no_offset.json
- spec/fixtures/files/air_table/records_with_offset.json
- spec/models/air_table_staff/csv_builder_spec.rb
- spec/models/air_table_staff/json_value_extractor_spec.rb
- spec/models/air_table_staff/record_list_spec.rb
- spec/models/air_table_staff/staff_directory_mapping_spec.rb
- spec/models/air_table_staff/staff_directory_person_spec.rb
- spec/models/air_table_staff/staff_list_job_spec.rb
- spec/support/stub_airtable.rb
- Even if the field names change slightly, our API calls should not break
- Request specific fields, to make it less likely that we accidentally pull private data (there should not be any in that sheet, but an extra safeguard seems like a good idea)
- Add a test helper for the airtable request, since the url is so long, and so we don't have to change it across tests
Connected to https://github.com/pulibrary/lib_jobs/issues/806
> I806 use field ids for airtable

- Gemfile
- Gemfile.lock
- config/environments/development.rb
I don't find it that useful while developing on lib_jobs, so simplifying things by removing it.  Definitely open to keeping it if others find it useful in this repo.
> Remove listen gem

- .rubocop.yml
- app/models/aspace_svn/get_eads_job.rb
this change explicitly enables the inclusion of `dao` tags in the EAD output
closes [aspace_helpers #609](https://github.com/pulibrary/aspace_helpers/issues/609)
> add daos to EAD output

- Gemfile
- Gemfile.lock
- app/models/aspace_version_control/get_eads_job.rb
- app/models/aspace_version_control/git_lab.rb
- app/models/aspace_version_control/svn.rb
- config/aspace.yml
- config/brakeman.ignore
- config/deploy.rb
- spec/models/aspace_version_control/get_eads_job_spec.rb
- spec/models/aspace_version_control/git_lab_spec.rb
Right now, the code runs the updates to SVN and GitLab in parallel. We can remove the SVN code once we are confident the GitLab code is working consistently as expected.
Connected to #877
> Add class to update EADs on GitLab

- spec/models/peoplesoft_voucher/voucher_feed_spec.rb
- spec/rails_helper.rb
Now that we have reached April 2025, we get a test failure with the following:
```
2021-03-30,PO-9999,XXX,111222333,1319.05,USD,124.94,A020RVUO,Invalid invoice date: must be between four years old and one month into the future
```
> Address test failure

- app/models/alma_people/oit_person_feed.rb
- spec/models/alma_people/oit_person_feed_spec.rb
When we type the following into `rails c` on lib-jobs-production:
```
data = AlmaPeople::OitPersonFeed.new.get_json(begin_date: '2025-06-11', end_date: '2025-06-12')
```
It is very slow, but eventually `data` is:
```
{'records'=>'record'=>[All the data is here in a single array]}
```
I believe our code is expecting `data` to be a single array, without `records` and `record`.
This PR is not ready yet, it only looks at `records`
> Alma People Feed: Update structure to match new OIT format

- config/schedule.rb
It will run in alma every week at 3am Princeton time
https://github.com/PrincetonUniversityLibrary/alma-config/issues/1794
> Disable alma_bib_norm task
